name: Deploy To Google Cloud Functions

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  deploy-gcf:
    name: Deploy to Google Cloud Functions
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to GCF
        uses: google-github-actions/deploy-cloud-functions@v2
        with:
          name: automaintainer-bot
          runtime: nodejs20
          entry_point: probotApp
          region: europe-west1
          source_dir: ./
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          env_vars: |
            APP_ID=${{ secrets.APP_ID }}
            PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}
            WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }}

