name: Deploy To Google Cloud Functions

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  deploy-gcf:
    name: Deploy to Google Cloud Functions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy function
        uses: google-github-actions/deploy-cloud-functions@v2
        with:
          name: automaintainer-bot
          runtime: nodejs20
          entry_point: automaintainer-bot
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          region: europe-west1
          source_dir: .
          env_vars: |
            NODE_ENV=production
            APP_ID=${{ secrets.APP_ID }}
            PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}
            WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }}
